version: '3.8'
services:
  webapp:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    ports:
      - '8080:80'
    volumes:
      - ./src:/var/www/html
    environment:
      - APACHE_RUN_USER=apache-www-volume
      - APACHE_RUN_GROUP=apache-www-volume
